nginx-ingress:
  controller:
    replicaCount: 3
    extraArgs:
      publish-service: kube-system/jxing-nginx-ingress-controller
    service:
      omitClusterIP: true
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-1:242867168342:certificate/7731015f-3053-4f30-829f-40c542243d1f
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
  defaultBackend:
    service:
      omitClusterIP: true
  rbac:
    create: true
