apiVersion: jenkins.io/v1
kind: Environment
metadata:
  name: stage
  namespace: jx
spec:
  kind: Permanent
  label: Stage
  namespace: stage
  order: 100
  previewGitInfo:
    user: {}
  promotionStrategy: Auto
  source:
    ref: master
    url: https://github.com/hibobio/environment-hibob-staging.git
  teamSettings:
    defaultScheduler:
      kind: ""
      name: ""
