external-dns:
  enabled: {{ .Requirements.ingress.externalDNS }}
  image:
    tag: 0.5.16-debian-9-r8
  sources:
  - ingress
  provider: aws
  aws:
    region: eu-west-1
    assumeRoleArn: arn:aws:iam::242867168342:role/k8s-external-dns
    preferCNAME: true
    txtPrefix: "a-"
  rbac:
    create: true
    serviceAccountName: external-dns
  domainFilters:
  - "{{ .Requirements.ingress.domain }}"
