adminUser:
  password: local:hibob-stage-dev-new/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: paz.talshachar@hibob.io
  token: local:hibob-stage-dev-new/pipelineUser:token
  username: hibob-jx
prow:
  hmacToken: local:hibob-stage-dev-new/prow:hmacToken
