tekton:
{{- if eq .Requirements.webhook "prow" }}
  enabled: true
{{- else if eq .Requirements.webhook "lighthouse" }}
  enabled: true
{{- else }}
  enabled: false
{{- end }}
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: "242867168342.dkr.ecr.eu-west-1.amazonaws.com"
